name: Publish zip

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish module zip
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        git archive --format zip -o ./module.zip ${{ github.ref }}

        RELEASES_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases
        cat <<EOF > update.json
        {
          "version": "$(sed -n "s|^version=||p" module.prop)",
          "versionCode": $(sed -n "s|^versionCode=||p" module.prop),
          "zipUrl": "$RELEASES_URL/latest/download/MyDNS-${{ github.ref }}.zip",
          "changelog": "$RELEASES_URL"
        }
        EOF

    - name: Upload zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ./module.zip
        asset_name: MyDNS-$tag.zip

    - name: Upload update.json to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ./update.json
